[package]
name = "sandbox-vulkan"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = "0.38.0"
sdl2 = "0.37.0"
image = "0.25.4"
tobj = "4.0.2"
imgui = "0.12.0"
imgui-rs-vulkan-renderer = "1.16.0"
imgui-sdl2-support = "0.13.0"
